---
docker_registry: "docker.io"
docker_namespace: "jbbillaud"
docker_project: "rakuten"

docker_repository: "{{ docker_registry }}/{{ docker_namespace }}/{{ docker_project }}"

docker_volumes:
  dvc: "dvc_data"
  postgres: "pgdata"
  logs: "logs_and_reports"

docker_network: "rakuten_network"