{
 "title": "Rakuten – Production Model Dashboard test",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(model_requests_total)" }
   ]
  },
  {
   "title": "Predictions / minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(model_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Average Confidence (last 5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(model_prediction_confidence_sum[5m])) / sum(rate(model_prediction_confidence_count[5m]))"
    }
   ]
  },
  {
   "title": "Entropy (Drift Indicator)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_entropy_last_value" }
   ]
  },
  {
   "title": "Confidence Histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(model_prediction_confidence_bucket[5m])",
     "legendFormat": "bucket {{le}}"
    }
   ]
  },
  {
   "title": "Entropy Histogram",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "rate(model_prediction_entropy_bucket[5m])",
     "legendFormat": "bucket {{le}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  }
 ]
}