---
- name: Check Podman CLI
  ansible.builtin.command:
    argv:
      - podman
      - --version
  register: podman_cli_version
  changed_when: false
  failed_when: false

- name: Install Podman
  ansible.builtin.apt:
    name:
      - podman
      - uidmap
      - slirp4netns
      - fuse-overlayfs
      - golang-github-containernetworking-plugin-dnsname
      - podman-compose
    state: present
    update_cache: true
    install_recommends: false
  become: true
  when:
    - podman_cli_version.rc != 0
    - ansible_facts.os_family | default('Debian') == "Debian"

- name: Create containers registries config directory
  ansible.builtin.file:
    path: /etc/containers/registries.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure Docker Hub as default registry
  ansible.builtin.copy:
    dest: /etc/containers/registries.conf.d/00-docker-hub.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      unqualified-search-registries = ["{{ podman_default_registry | default(docker_registry | default('docker.io')) }}"]

- name: Login to Docker Hub with Podman
  ansible.builtin.include_tasks: login_docker_hub.yaml

- name: Login to DHI with Podman
  ansible.builtin.include_tasks: login_dhi.yaml
