---
docker_registry: "docker.io"
docker_namespace: "jbbillaud"
docker_project: "rakuten"

docker_repository: "{{ docker_registry }}/{{ docker_namespace }}/{{ docker_project }}"

docker_infra: "{{ lookup('ansible.builtin.file', inventory_dir ~ '/../../config/docker.yaml') | from_yaml }}"

docker_volumes: "{{ docker_infra.volumes }}"
docker_volume_items: "{{ docker_infra.volumes | dict2items }}"
docker_volume_names: "{{ docker_volume_items | map(attribute='value') | list }}"

docker_network: "{{ docker_infra.network.name }}"

ansible_vault_file: "{{ inventory_dir }}/group_vars/all/secrets.vault.yaml"
