services:
  minio: # ne pas modifier le nom
    image: minio/minio:${MINIO_VERSION}
    container_name: minio-S3-storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - dvc_data:/mount
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio-client: # ne pas modifier le nom
    image: jbbillaud/rakuten:minio-client-${MC_VERSION:-RELEASE.2025-08-13T08-35-41Z}
    container_name: minio-client
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      MINIO_MLFLOW_BUCKET: ${MINIO_MLFLOW_BUCKET}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - dvc_data:/dvc_data
    command: "/src/minio_init.sh > /proc/1/fd/1 2>&1"
    tty: true

  dvc:
    image: jbbillaud/rakuten:dvc-v3.66.1
    container_name: dvc
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - dvc_data:${WORKDIR}/dvc_data
      - pgdata:${WORKDIR}/pgdata
      - logs_and_reports:${WORKDIR}/logs_and_reports

networks:
  default:
    name: docker-network

volumes:
  pgdata:
    name: pgdata
    external: false
  minio_data:
    name: minio_data
    external: false
  dvc_data:
    name: dvc_data
    external: false
  logs_and_reports:
    name: logs_and_reports
    external: false
