# infra/ansible/playbooks/install_pixi.yml
---

- name: Install local softwares
  hosts: all
  gather_facts: true
  serial: 1
  become: true

  tasks:
    - name: Install and configure Podman
      ansible.builtin.include_tasks: tasks/podman/install_podman.yaml

    - name: Install snap
      ansible.builtin.include_tasks: tasks/utils/install_snap.yaml

    - name: Install Terraform
      ansible.builtin.include_tasks: tasks/terraform/install_terraform.yaml

    - name: Install Infisical CLI
      ansible.builtin.include_tasks: tasks/infisical/install_infisical_cli.yaml

    - name: Install Bitwarden CLI
      community.general.snap:
        name: bw
        state: present
