# infra/ansible/playbooks/install_nvidia_gpu_stack.yaml
---
- name: Install NVIDIA GPU stack
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Detect NVIDIA driver
      ansible.builtin.import_tasks: tasks/nvidia/detect_nvidia_driver.yaml

    - name: Install NVIDIA driver if needed
      ansible.builtin.import_tasks: tasks/nvidia/install_nvidia_driver.yaml
      when: not nvidia_driver_installed

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.import_tasks: tasks/nvidia/install_nvidia_container_toolkit.yaml

    - name: Configure NVIDIA runtime
      ansible.builtin.import_tasks: tasks/nvidia/configure_nvidia_runtime.yaml