# tasks/build_one_image.yaml

- name: Prepare image build config
  ansible.builtin.include_tasks: tasks/docker_images/prepare_build_image.yaml

- name: Build docker image {{ build_image.repository }}:{{ build_image.tag }}
  containers.podman.podman_image:
    name: "{{ build_image.repository }}"
    tag: "{{ build_image.tag }}"
    path: "{{ build_image.build_context }}"
    build:
      file: "{{ build_image.dockerfile_path }}"
      force_rm: true
      extra_args : >-
        --build-arg PIXI_ENV="{{ build_image.name }}" 
        --build-arg PIXI_CATALOG_DIR="{{ catalog_dir_from_context }}"
        --build-arg DVC_VOLUME_DIR="{{ docker_volumes.dvc }}"
        --build-arg POSTGRES_VOLUME_DIR="{{ docker_volumes.postgres }}"
        --build-arg LOGS_VOLUME_DIR="{{ docker_volumes.logs }}"
        --build-arg DOCKERFILE_ROOT="{{ build_image.dockerfile_root }}"
        --build-arg INFISICAL_CLI_IMAGE="{{ infisical_cli_image }}"
    force: "{{ force_rebuild | default(false) }}"
    push: "{{ push | default(true) }}"
  environment:
    REGISTRY_AUTH_FILE: "{{ ansible_facts.env.HOME }}/.config/containers/auth.json"
