;[local]
;localhost ansible_connection=local

[dev]
rakuten_dev ansible_connection=local

[deploy]
rakuten_deploy ansible_connection=local ansible_python_interpreter=/usr/bin/python3

;[gpu_nodes]
;rakuten_gpu_nodes ansible_connection=local
