# ======================
# 🔧 Configuration globale de la pipeline
# ======================

# 📁 Chemins
data:
  raw_dir: data/raw/latest
  processed_dir: data/processed/
#  interim_dir: data/interim/

image_model:
  image_force_training: True
  image_model_path: models/image/

text_model:
  text_force_training : True
  text_model_path: models/text/

# ⚙️ Paramètres d'entraînement
training:
  output_dir: outputs/
  epochs: 20
  batch_size: 256
  random_state: 42
  early_stopping_patience: 5
  target_size: 2000           # nombre max d’échantillons par classe après balancing

multithreading:
  activate: True
  auto: True # prendra la valeur min entre 8 et le nombre de threads logiques // 2
  num_workers: 10

# 🧠 Choix des modèles
models:
  image: "xgboost"   # ou "mlp"
  text: "svm"

# 🔄 Contrôle du pipeline
force_preprocessing: True
save_outputs: True

# 🤝 Fusion multimodale
fusion_strategy: "mean"       # options : mean, product, max, weighted, confidence_weighted

# 🧪 Évaluation avancée
crossval_folds: 5
optuna_trials: 50

# ======================
# ⛔ Ne pas modifier ⛔
# ======================

version: 1 # latest doit toujours pointer vers ce numéro