# tasks/ansible_vault/create_github_secrets.yaml
---
- name: Read GitHub App private key if provided
  ansible.builtin.set_fact:
    github_app_private_key: >-
      {{ lookup('ansible.builtin.file', vault_github_private_key_path)
         if (vault_github_private_key_path | length > 0) else '' }}
  no_log: true

- name: Build dictionary for GitHub secrets
  ansible.builtin.set_fact:
    github_secret:
      github_app:
        app_id: "{{ vault_github_app_id }}"
        client_id: "{{ vault_github_client_id }}"
        installation_id: "{{ vault_github_installation_id }}"
        private_key: "{{ github_app_private_key }}"
  no_log: true