# tasks/ansible_vault/create_postgres_secrets.yaml
---
- name: Generate password for {{ postgres_service.name }}
  ansible.builtin.command:
    cmd: openssl rand -hex 32
  register: generated_password
  changed_when: true
  no_log: true

- name: Build dictionary for {{ postgres_service.name }}
  ansible.builtin.set_fact:
    current_service_secret:
      "{{ postgres_service.name }}":
        db: "{{ postgres_service.db }}",
        user: "{{ postgres_service.user }}"
        password: "{{ generated_password.stdout }}"
  no_log: true

- name: Accumulate service secret
  ansible.builtin.set_fact:
    postgres_secrets: >-
      {{
        postgres_secrets | default({})
        | combine(current_service_secret, recursive=True)
      }}
  no_log: true