# tasks/ansible_vault/create_service_secrets.yaml
---
- name: Generate password for {{ service.name }}
  ansible.builtin.command:
    cmd: openssl rand -hex 32
  register: generated_password
  changed_when: true
  no_log: true

- name: Generate Airflow Fernet key
  ansible.builtin.command:
    argv:
      - python3
      - -c
      - "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())"
  register: generated_password
  when: service.name == "airflow"
  changed_when: true
  no_log: true

- name: Build dictionary for {{ services.name }}
  ansible.builtin.set_fact:
    current_service_secret:
      "{{ service.name }}":
        user: "{{ service.user }}"
        password: "{{ generated_password.stdout }}"
  no_log: true

- name: Accumulate service secret
  ansible.builtin.set_fact:
    services_secrets: >-
      {{
        services_secrets | default({})
        | combine(current_service_secret, recursive=True)
      }}
  no_log: true