# tasks/ansible_vault/create_dagshub_secrets.yaml
---
- name: Build dictionary for dagshub secrets
  ansible.builtin.set_fact:
    dagshub_secret:
      dagshub:
        user: "{{ vault_dagshub_user }}"
        password: "{{ vault_dagshub_password }}"
  no_log: true