# tasks/ansible_vault/create_minio_service_accounts.yaml
---
- name: Read existing MinIO service account secret for {{ minio_service_account.name }}
  ansible.builtin.set_fact:
    existing_minio_service_account_secret: >-
      {{
        (
          (minio_service_accounts | default({}))[minio_service_account.name] | default({})
        ).secret_key | default('')
      }}
  no_log: true

- name: Generate MinIO service account secret for {{ minio_service_account.name }}
  ansible.builtin.command:
    cmd: openssl rand -hex 32
  register: generated_minio_service_account_secret
  changed_when: true
  when:
    - vault_force_recreate | bool or existing_minio_service_account_secret | length == 0
  no_log: true

- name: Select MinIO service account secret for {{ minio_service_account.name }}
  ansible.builtin.set_fact:
    current_minio_service_account_secret: >-
      {{
        generated_minio_service_account_secret.stdout
        if (vault_force_recreate | bool or existing_minio_service_account_secret | length == 0)
        else existing_minio_service_account_secret
      }}
  no_log: true

- name: Build MinIO service account dictionary for {{ minio_service_account.name }}
  ansible.builtin.set_fact:
    current_minio_service_account_secret_dict: >-
      {{
        {
          'minio_service_accounts': {
            minio_service_account.name: {
              'access_key': (
                (
                  (minio_service_accounts | default({}))[minio_service_account.name] | default({})
                ).access_key | default(minio_service_account.access_key)
              ),
              'secret_key': current_minio_service_account_secret
            }
          }
        }
      }}
  no_log: true

- name: Accumulate MinIO service account secrets
  ansible.builtin.set_fact:
    minio_service_account_secrets: >-
      {{
        minio_service_account_secrets | default({})
        | combine(current_minio_service_account_secret_dict, recursive=True)
      }}
  no_log: true
