global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "preprocessing"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["data:8001"]

  - job_name: "model-serving"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["model-serving:8002"]

  - job_name: "airflow-statsd"
    static_configs:
      - targets: [ "statsd-exporter:9102" ]
