# infra/ansible/tasks/detect_nvidia_driver.yaml
---
- name: Check NVIDIA driver with nvidia-smi
  ansible.builtin.command:
    cmd: nvidia-smi
  register: nvidia_smi_check
  failed_when: false
  changed_when: false

- name: Check NVIDIA driver proc file
  ansible.builtin.stat:
    path: /proc/driver/nvidia/version
  register: nvidia_driver_proc

- name: Define NVIDIA driver state
  ansible.builtin.set_fact:
    nvidia_driver_installed: "{{ nvidia_smi_check.rc == 0 or nvidia_driver_proc.stat.exists }}"

