# ======================
# 🔧 Configuration globale de la pipeline
# ======================

# 📁 Chemins
data_path: "../data"
model_path: "../data/models"
image_dir: "../data/images"
output_dir: "../data/reports"
plot_dir: "../data/plots"

# ⚙️ Paramètres d'entraînement
batch_size: 32
target_size: 2000           # nombre max d’échantillons par classe après balancing
random_state: 42
num_workers: -1
early_stopping_patience: 5

# 🧠 Choix des modèles
image_model_type: "xgboost"   # ou "mlp"
text_model_type: "svm"

# 🔄 Contrôle du pipeline
force_preprocessing: false
save_outputs: true

# 🤝 Fusion multimodale
fusion_strategy: "mean"       # options : mean, product, max, weighted, confidence_weighted

# 🧪 Évaluation avancée
crossval_folds: 5
optuna_trials: 50
