# infra/ansible/playbooks/install_pixi.yml
---

- name: Install dev tools
  hosts: all
  gather_facts: true

  tasks:
    - name: Install Pixi
      ansible.builtin.include_tasks: tasks/install_pixi.yaml

    - name: Install Podman
      ansible.builtin.apt:
        name:
          - podman
        state: present
        update_cache: true
        install_recommends: false